export const GET_ORDER_LIST='order/GET_ORDER_LIST';
export const SEARCH_ORDER_SUCCESS='order/SEARCH_ORDER_SUCCESS';
export const GET_ORDER_DETAIL_SUCCESS='order/GET_ORDER_DETAIL_SUCCESS';
export const GO_SET_ORDER_SUCCESS='order/GO_SET_ORDER_SUCCESS';