export const SET_CATEGORY='goods/SET_CATEGORY';
export const SET_IMAGE='goods/SET_IMAGE';
export const SET_DETAIL='goods/SET_DETAIL';
export const ADD_GOODS='goods/ADD_GOODS';
export const SET_GOODS_ERROR='goods/SET_GOODS_ERROR';
export const SET_IMAGES_ERROR='goods/SET_IMAGES_ERROR';
export const GET_GOODS_LIST='goods/GET_GOODS_LIST';
export const UPDATE_GOODS_ORDER_SUCCESS='goods/UPDATE_GOODS_ORDER_SUCCESS';
export const EDIT_GOODS_SUCCESS='goods/EDIT_GOODS_SUCCESS';
export const UPDATE_GOODS_STATUS_SUCCESS='goods/UPDATE_GOODS_STATUS_SUCCESS';
export const SEARCH_GOODS_SUCCESS='goods/SEARCH_GOODS_SUCCESS';
export const GET_GOODS_DETAIL_SUCCESS='goods/GET_GOODS_DETAIL_SUCCESS';


